### ISSUE TITLE
Consider publishing lozft source

### ISSUE THREAD

**Issue by gzip** [TheRealQuantam/makeftromtutorial#1]
The tutorial mentions lozft but the only other reference I can find to it has dead links:
https://www.romhacking.net/forum/index.php?topic=37261.0

I happen to have a copy of the archive but it doesn't contain source code. Would you consider posting it here on github like you've already done for mm2ft?

(I posted a similar message on rhdn but it's stuck in moderation.)

**Comment by TheRealQuantam** [comment]
I've uploaded lozft v0.1 to https://archive.org/details/lozft-v0.1

**Comment by gzip** [comment]
Thanks for uploading that but it's the same package that I already have with no source code. Do you have source that you can commit to github?
